- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card_show.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/destinations_controller.rb
- app/controllers/pages_controller.rb
- app/views/destinations/show.html.erb
- lausanne_paris.json
Alors, j'ai récupérer les informations de l'api. il m'en manque encore certaines, comme par exemple le prix du trajet, les dates de départ et d'arrivée (probablement à récupérer du formuaire search dans index) et l'empreinte carbone. 
POur le moment, j'ai fait une mise en page basique, je dois encore bien la retravailler !
> IW show name and description

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_fonts.scss
- app/javascript/components/navbar.js
- app/javascript/packs/application.js
- app/views/destinations/show.html.erb
- app/views/shared/_navbar.html.erb
J'ai modifié le logo dans la navbar, ca ressemble à ça (no comment please ;) ):
et j'ai ajouté du js pour que la barre deviennent visible uniquement lorsqu'on scroll vers le bas.
> Changed logo and added js to navabr

- app/controllers/destinations_controller.rb
J'ai juste modifié dans mon controller l'url pour la requête api google (je t'ai copié Justine)
> Modified key api in controller

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_form_research.scss
- app/javascript/plugins/flatpickr.js
- app/models/destination.rb
- app/views/destinations/index.html.erb
Le formulaire terminé mais avec le problème de geocoder.
> Nv add time to form

- app/controllers/destinations_controller.rb
- app/views/destinations/index.html.erb
- app/views/destinations/show.html.erb
- app/views/shared/_card-destination-driving.html.erb
- app/views/shared/_card-destination.html.erb
- berlin_sarande_driving.json
J'ai modifié la show dans le controller, en particulier l'url de l'api. J'ai pu rentrer les données obtenues dans le formulaire de l'index pour l'origine, date et heure de départ. Tout fonctionne bien. Et lorsqu'il n'y a pas de possibilités par train, j'ai mis un message: pas possible d'y aller en transport public pour le moment.
> Modifed show

- app/controllers/destinations_controller.rb
- app/views/destinations/index.html.erb
- app/views/shared/_text_index.html.erb
Avant la recherche
Après la recherche
> index whith text

- app/controllers/pages_controller.rb
- app/views/destinations/index.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_home_logout.html.erb
- app/views/shared/_text_index.html.erb
- config/routes.rb
> route home

- app/controllers/application_controller.rb
- app/controllers/destinations_controller.rb
- app/controllers/favorites_controller.rb
- app/models/destination.rb
- app/models/favorite.rb
- app/models/user.rb
- app/views/destinations/index.html.erb
- config/routes.rb
- db/migrate/20190529143835_create_favorites.rb
- db/schema.rb
- test/controllers/favorites_controller_test.rb
- test/models/favorite_test.rb
L'action ajouté aux favoris est crée. Maintenant je dois créer la page des favoris
> Nv favorites

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_form_research.scss
- app/assets/stylesheets/components/_index.scss
- app/views/destinations/index.html.erb
- app/views/shared/_form_research.html.erb
> Jt front home

- app/assets/stylesheets/components/_card_show.scss
- app/controllers/destinations_controller.rb
- app/javascript/components/card_click.js
- app/views/destinations/index.html.erb
- app/views/layouts/application.html.erb
Sur la vue de l'index, on peut voir différents parcours pour une destination (classé par empreinte carbone du plus petit au plus grand):
> Show index

- app/assets/stylesheets/components/_card_show.scss
- app/controllers/destinations_controller.rb
- app/helpers/hash_hidden_tag.rb
- app/views/destinations/index.html.erb
- app/views/destinations/show.html.erb
- app/views/shared/_card-destination.html.erb
J'ai enfin réussi à faire fonctionner l'index et la show (avec l'aide de Justine, mille mercis !!!!!).
Donc à présent, dans l'index, on peut bien voir tous les parcours pour deux destinations (j'ai réduit le nombre pour le moment, ça se change très facilement par la suite).
Et du coup, si on veut voir plus de détails, on arrive sur la show en appuyant sur le lien :)
> Iw problem between index and show

- app/assets/stylesheets/components/_card_index.scss
- app/controllers/favorites_controller.rb
- app/views/destinations/index.html.erb
- app/views/favorites/list.html.erb
- config/routes.rb
Ajouter dans favoris
Déjà ajouté dans favoris
Il y a beaucoup de blanch entre le nom de la destination et la description car il manque le bouton supprimer le favoris. Je m'en occupe demain avec sa méthode
> Nv favorites page

- app/assets/stylesheets/application.scss
- app/views/destinations/index.html.erb
J'ai ajouté le linear gradient de nico dans le background de toute l'application.
> Jt background color

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card_index.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/destinations/index.html.erb
> Jt form suite

- app/assets/stylesheets/components/_navbar.scss
- app/javascript/components/navbar.js
- app/views/shared/_navbar.html.erb
La barre quand loggé: 
la barre quand pas loggé:
> Modifier navbar

- app/assets/stylesheets/components/_form.scss
- app/views/destinations/index.html.erb
Ca devrait etre bon pour le petit bug de banner qui se superpose.
> fixing banner issues

- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
j'ai juste ajouté la div main-container sur tous les form de sign in et up
> Ajouter container au sign in et sign up

- app/assets/stylesheets/components/_article.scss
- app/assets/stylesheets/components/_index.scss
- app/views/shared/_form_research.html.erb
- app/views/shared/_home_logout.html.erb
> Content home

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card_index.scss
- app/assets/stylesheets/components/_card_show.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/destinations/show.html.erb
- app/views/shared/_card-destination-index.html.erb
- app/views/shared/_card-destination-show.html.erb
- app/views/shared/_navbar.html.erb
Le layout de la show (pour le moment), en suivant au mieux les instructions de Nico:
> Iw show layout

- app/assets/stylesheets/components/_card_index.scss
- app/assets/stylesheets/components/_card_show.scss
- app/javascript/components/card_click.js
- app/views/favorites/list.html.erb
- app/views/shared/_card-destination-show.html.erb
J'ai modifié le code js, à présent, on peut appuyer sur les flèches uniquement pour montrer les différents parcours (versus auparavant où on pouvait appuyer n'importe où sur la carte). De plus, j'ai aussi réglé le problème de devoir appuyer deux fois sur la carte, maintenant tout fonctionne correctement :)
> Iw fixed js index

- app/controllers/destinations_controller.rb
- app/views/shared/_card-destination-index.html.erb
- app/views/shared/_navbar.html.erb
J'ai créé une méthode pour qu'on puisse afficher la date de départ et d'arrivée, même si l'arrivée se fait le lendemain (dans le cas de train de nuit par ex.).
Je devrais encore ajouter ça à la show et au travel diary (demain :) )
> Iw methode date

- app/views/shared/_form_research.html.erb
J'ai juste supprimé la classe bootstrap du bouton du formulaire de recherche, qui rendait le bouton gris quand ça chargeait.
> delete bootstrap btn class

- app/controllers/steps_controller.rb
- app/views/shared/_card-destination-show.html.erb
- app/views/steps/traveldiary.html.erb
- db/migrate/20190603193811_add_arrival_day_to_steps.rb
- db/schema.rb
Faire DB:MIGRATE !
J'ai ajouté la date d'arrivée sur le travel diary, et sur la show la date de départ et d'arrivée:
> Ajouter date dans show et travel diary

- app/controllers/destinations_controller.rb
- app/services/api_request.rb
- app/services/api_request_service.rb
- app/views/shared/_form_research.html.erb
J'ai créé un service pour notre api request, du coup tout à l'air de fonctionné comme ça !
Maintenant dans le controller de destination, on a juste la méthode index, show + une méthode privée!
> Iw refracto destination controller

- app/controllers/destinations_controller.rb
- app/services/api_request_service.rb
- app/views/shared/_form_research.html.erb
Petite méthode pour modifier le champ heure:
> Iw modifier champ heure

- app/controllers/destinations_controller.rb
- app/views/destinations/index.html.erb
- app/views/destinations/index.js.erb
- app/views/shared/_form_research.html.erb
J'ai modifier la recherche de l'index pour la faire en ajax.
> Ajouter ajax à la recherche sur index

- app/assets/stylesheets/components/_card_index.scss
- app/assets/stylesheets/components/_legend.scss
- app/assets/stylesheets/components/_steps.scss
- app/models/destination.rb
- app/views/shared/_card-destination-index.html.erb
- app/views/shared/_legend_icons.html.erb
- app/views/steps/traveldiary.html.erb
> Nv general front

- app/assets/stylesheets/components/_steps.scss
- app/controllers/destinations_controller.rb
- app/controllers/steps_controller.rb
- app/views/shared/_form_patch_description_traveldiary.html.erb
- app/views/shared/_form_research.html.erb
- app/views/steps/traveldiary.html.erb
- app/views/steps/update.js.erb
J'ai ajouté le point de départ du voyage dans le travel diary
De plus, si on clique sur "next step?", la case de location dans le search-form est déjà rempli du nom de la dernière destination du travel diary.
Finalement, j'ai ajouté de l'ajax sur la méthode update, pour que lorsqu'on modifie une description et qu'on clique sur "YES", alors la page n'a pas besoin d'être redirigé.
> Iw modif travel diary

- app/assets/stylesheets/components/_card_index.scss
- app/assets/stylesheets/components/_spinner.scss
- app/assets/stylesheets/components/loader.js
- app/javascript/components/spinner.js
- app/views/destinations/index.html.erb
- app/views/shared/_home_logout.html.erb
Le spinner fonctionne assez bien normalement ! A vous de tester :)
> Spinner fonctionne

- app/controllers/destinations_controller.rb
- app/services/api_request_service.rb
A présent, on a des destinations sympas qui sont différentes des endroits où on est déjà allé !
> Modifier les destinations qui apparaissent lors du search

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_carbon_index.scss
- app/assets/stylesheets/components/_card_index.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/views/shared/_card-destination-index.html.erb
- app/views/shared/_home_logout.html.erb
> card carbon index

- app/assets/stylesheets/components/_spinner.scss
- app/javascript/components/spinner.js
- app/views/destinations/index.js.erb
J'ai revu le positonnement du train, j'espère que c'est mieux comme ça !
> Modifier positionnement du train

- db/seeds/seed_user.rb
J'ai modifié les descriptions de la seed, et la destination Amsterdam pour Odense(Denmark) !
La seule description que je n'ai pas modifiée, c'est celle de Lausanne. Et tous les commentaires sont en anglais, je me suis dit que c'était plus logique de tous avoir en anglais et de pas commencer à ajouter du français.
> Iw modifier seed

- app/assets/stylesheets/components/_spinner.scss
- app/views/steps/update.js.erb
La description s'update bien en ajax
> Modifier ajax pour update travel diary

- app/services/api_request_service.rb
- app/views/shared/_card-destination-index.html.erb
- app/views/shared/_card-destination-show.html.erb
J'ai ajouté des prix pour l'index. J'ai fait en sorte qu'un prix soit décidé pour une destination entre 80 et 130, et après pour les différents parcours de cette destination, le prix varie jusqu'à max 20 CHF.
> Modifier les prix index et show
